### PR TITLE
Add new features and improve database query and code

### PR DESCRIPTION
**Pull request by hermanntoast**
- Add new commandline Option: --outdated, --lastbackup, --enablemsg, --usehtml
- Add outdated for not running backups
- Add enablemsg to append the errormessage
- Add usehtml to make integration in other monitoring systems possible
- Add lastbackup support to only show the latest backup

### CODE REVIEW

**Comment by dnsmichi** [comment]
Cool, thank you 👍 Since I don't have a test environment, could you please be so kind and share some sample plugin calls and their output? (or Icinga Web 2 screenshots).

**Review by mxhash — CHANGES_REQUESTED** [review]
Thanks for the PR. What is the reason for the wpreston svn id comment? Also please have a look for mixed whitespace characters.

Cheers,
Marius

**Comment by hermanntoast** [comment]
Thank you for your comments. Hope the changes are like you thought so.

If you have any ideas please tell me!

**Comment by mxhash** [comment]
Hi,

Thank you! I added a couple of small fixes. Still works and are u ok with that?

Cheers,
Marius

**Review by mxhash — APPROVED** [review]

**Comment by hermanntoast** [comment]
Sure. Sounds good!

Thank you!

**Comment by mxhash** [comment]
LGTM, thank you!

**Pull request merged**
